### PR TITLE
Fix #154: Crash while fast clicking on session item

### LINKED ISSUE #154: Crash while fast clicking on session item
http://crashes.to/s/e9bce8d29f1

[br.org.cesar.discordtime.stickysessions_issue_4_crash_5C6AE18900BA000167B459822C74DB2A_DNE_0_v2.txt](https://github.com/DiscordTime/sticky-sessions-android/files/2876680/br.org.cesar.discordtime.stickysessions_issue_4_crash_5C6AE18900BA000167B459822C74DB2A_DNE_0_v2.txt)

### PR DESCRIPTION
**Pull request by CarlosRodrigo**
The presenter was detaching the view on the onPause method that was being called on the onPause android lifecycle method therefore when the user presses another time the mView property was not present resulting in a NullPointerException. I changed the lifecycle events from onPause to onStop and onResume to onStart.

### CODE REVIEW

File: app/src/main/java/br/org/cesar/discordtime/stickysessions/presentation/list/ListSessionsPresenter.java [hunk 1]
```diff
@@ -58,7 +58,7 @@ public void onLoad() {
     }
 
     @Override
-    public void onPause() {
+    public void onStop() {
```
Comment (rodrigoperazzo) [inline app/src/main/java/br/org/cesar/discordtime/stickysessions/presentation/list/ListSessionsPresenter.java]: We could also include a check for `mView != null` on Presenter's entry points.

Comment (CarlosRodrigo) [reply app/src/main/java/br/org/cesar/discordtime/stickysessions/presentation/list/ListSessionsPresenter.java]: Sure. I'll add it.
